import Head from "next/head";
import HomeCosmetics from "./home-cosmetics";

export default function Home({ title }) {
  return (
    <>
      <Head>
        <title>The Science of Herbs</title>
        <meta name="description" content="Generated by Kalles" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main>
        <HomeCosmetics />
      </main>
    </>
  );
}